### ISSUE TITLE
One wavin sensor shows wrong temperature

### ISSUE THREAD

**Issue by MicOestergaard** [heinekmadsen/esphome_components#39]
I just set up the V2 of the wavin component and it works great. The only problem is that one of the sensors always shows 0,9 degrees. Otherwise the sensor works correctly. The setpoint, whether it is on or off, works fine. The battery level seems correct. It's only the temperature for one sensor that is off.

Two of the sensors control two strings each, so I had to do the channel offsets for the sensors, but that works great. I have tried enabling all the other sensors and they show 0 degrees correctly.

Since the numbers for the sensors seem to depend on the order in which they are added, I removed all thermostats and added them back in order starting from channel 1. That made the temperature (and battery) sensors match the channel numbers.

Finally I tried using the latest version of ESPHome instead of 2022.5.1, but that just returned weird values.

ESPHome configuration:
 
```
########################################################################################
#                      CONFIGURATION PART OF YOUR CHOICE :)                            #
########################################################################################

substitutions:
  # UNIQUE NAME FOR THE DEVICE
  device: wavin # Case sensitive!!!
  name: Wavin   # "Friendly name" - not case sensitive!!!
  
  # CHANNEL friendly names (If using spaces remember to add ")
  channel_01_friendly_name: "Stue"
  channel_02_friendly_name: "Alrum"
  channel_03_friendly_name: "Bryggers"
  channel_04_friendly_name: "Lille badeværelse"
  channel_05_friendly_name: "Værelse 2"
  channel_06_friendly_name: "Værelse 1"
  channel_07_friendly_name: "Gang"
  channel_08_friendly_name: "Channel 08"
  channel_09_friendly_name: "Channel 09"
  channel_10_friendly_name: "Stort badeværelse"
  channel_11_friendly_name: "Soveværelse"
  channel_12_friendly_name: "Channel 12"
  channel_13_friendly_name: "Channel 13"
  channel_14_friendly_name: "Channel 14"
  channel_15_friendly_name: "Channel 15"
  channel_16_friendly_name: "Channel 16"
  
  # CHANNEL ID´S (ONLY LOWER CASE LETTERS, NO SPACES) used for entity ids
  channel_01_id: stue
  channel_02_id: alrum
  channel_03_id: bryggers
  channel_04_id: lille_badevaerelse
  channel_05_id: vaerelse_2
  channel_06_id: vaerelse_1
  channel_07_id: gang
  channel_08_id: channel_08
  channel_09_id: channel_09
  channel_10_id: stort_badevaerelse
  channel_11_id: sovevaerelse
  channel_12_id: channel_12
  channel_13_id: channel_13
  channel_14_id: channel_14
  channel_15_id: channel_15
  channel_16_id: channel_16

 # CHANNEL Alignments (ONLY change if you have offsets in channel vs temperature. Some have reported this if using multiple strings pr. room thermostat)
  channel_01_sensor: "0x00"
  channel_02_sensor: "0x01"
  channel_03_sensor: "0x02"
  channel_04_sensor: "0x03"
  channel_05_sensor: "0x04"
  channel_06_sensor: "0x05"
  channel_07_sensor: "0x06"
  #channel_08_sensor: "0x07"
  #channel_09_sensor: "0x08"
  channel_10_sensor: "0x07"
  channel_11_sensor: "0x08"
  #channel_12_sensor: "0x09"
  #channel_13_sensor: "0x0A"
  #channel_14_sensor: "0x0B"
  #channel_15_sensor: "0x0C"
  #channel_16_sensor: "0x0D"
  
  channel_01: "0x00"
  channel_02: "0x01"
  channel_03: "0x02"
  channel_04: "0x03"
  channel_05: "0x04"
  channel_06: "0x05"
  channel_07: "0x06"
  #channel_08: "0x07"
  #channel_09: "0x08"
  channel_10: "0x09"
  channel_11: "0x0A"
  #channel_12: "0x0B"
  #channel_13: "0x0C"
  #channel_14: "0x0D"
  #channel_15: "0x0E"
  #channel_16: "0x0F"

   # UPDATE TIME (GATEWAY)
  update_interval: 60s
 
  # PIN DEFINITIONS (Should in most cases not be changed) 
  rx_pin: '20'
  tx_pin: '21'
 
  # WiFi settings
  ssid_set: !secret wifi_ssid
  password_set: !secret wifi_password
 
########################################################################################
#                        CODE BELOW SHOULD NOT BE CHANGED                              #
########################################################################################  
 
esphome:
  name: ${device}
  
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
  
# Enable logging
logger:
  baud_rate: 0
 
# Enable Home Assistant API
api:
 
ota:
  platform: esphome
 
wifi:
  ssid: ${ssid_set}
  password: ${password_set}
 
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wavin Fallback Hotspot"
    password: ""
 
captive_portal:  
 
uart:
  - id: uart_${device}
    rx_pin: ${rx_pin}
    tx_pin: ${tx_pin}
    baud_rate: 38400
    stop_bits: 1
    parity: NONE
 
modbus:
    - id: ${device}_modbus
      uart_id: uart_${device}
      flow_control_pin: 10
 
modbus_controller:
  id: ${device}_modbus_controller
  address: 1
  modbus_id: ${device}_modbus
  update_interval: ${update_interval}
 
packages:
  remote_package:
    url: https://github.com/dkgof/esphome_components
    ref: main
    files:
      - components/wavinahc9000v2/configs/basic.yaml # REQUIRED FOR WAVIN AHC 9000
      - components/wavinahc9000v2/configs/channel_01.yaml
      - components/wavinahc9000v2/configs/channel_02.yaml
      - components/wavinahc9000v2/configs/channel_03.yaml
      - components/wavinahc9000v2/configs/channel_04.yaml
      - components/wavinahc9000v2/configs/channel_05.yaml
      - components/wavinahc9000v2/configs/channel_06.yaml
      - components/wavinahc9000v2/configs/channel_07.yaml
      #- components/wavinahc9000v2/configs/channel_08.yaml
      #- components/wavinahc9000v2/configs/channel_09.yaml
      - components/wavinahc9000v2/configs/channel_10.yaml
      - components/wavinahc9000v2/configs/channel_11.yaml
      #- components/wavinahc9000v2/configs/channel_12.yaml
      #- components/wavinahc9000v2/configs/channel_13.yaml
      #- components/wavinahc9000v2/configs/channel_14.yaml
      #- components/wavinahc9000v2/configs/channel_15.yaml
      #- components/wavinahc9000v2/configs/channel_16.yaml
    refresh: 0s
```

Home Assistant:

<img width="312" alt="Image" src="https://github.com/user-attachments/assets/6d5da1e8-5af9-4e61-bbd9-f69e9130b90d" />
