### ISSUE TITLE
V2 - Channel 9 and 10 is showing temperature at 0 degrees celcius

### ISSUE THREAD

**Issue by mathias-jakobsen** [heinekmadsen/esphome_components#9]
I just set up the V2 of the wavin component. It all works splendid, except for channel 9 and 10, which always shows the current temperature at 0 degrees celcius. See picture below.
The climate control works as expected.

ESPHome configuration:
```
substitutions:
  device: "wavin"
  name: "Wavin"
  log_level: DEBUG

  channel_01_friendly_name: "Kitchen-Dining Room"
  channel_02_friendly_name: "Guest Toilet"
  channel_03_friendly_name: "test1"
  channel_04_friendly_name: "test2"
  channel_05_friendly_name: "Bedroom"
  channel_06_friendly_name: "Walk In"
  channel_07_friendly_name: "Walkthrough"
  channel_08_friendly_name: "Bathroom"
  channel_09_friendly_name: "Playroom"
  channel_10_friendly_name: "Child's Room"
  channel_11_friendly_name: "test4"
  channel_12_friendly_name: "test5"
  channel_13_friendly_name: "test6"
  channel_14_friendly_name: "test7"
  channel_15_friendly_name: "test8"
  channel_16_friendly_name: "test9"
  
  channel_01_id: kitchen_dining_room
  channel_02_id: guest_toilet
  channel_03_id: test1
  channel_04_id: test2
  channel_05_id: bedroom
  channel_06_id: walk_in
  channel_07_id: walkthrough
  channel_08_id: bathroom
  channel_09_id: playroom
  channel_10_id: childs_room
  channel_11_id: test4
  channel_12_id: test5
  channel_13_id: test6
  channel_14_id: test7
  channel_15_id: test8
  channel_16_id: test9

  ssid_set: <redacted>
  password_set: <redacted>

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m
  project:
    name: "home.wavin_gulvvarme"
    version: "1.0.0"

logger:
  baud_rate: 0
    
api:
  
ota:
  password: <redacted>

wifi:
  ssid: ${ssid_set}
  password: ${password_set}

  manual_ip:
    static_ip: <redacted>
    gateway: <redacted>
    subnet: <redacted>

  ap:
    ssid: <redacted>
    password: <redacted>

captive_portal:  

packages:
  remote_package:
    url: https://github.com/heinekmadsen/esphome_components
    ref: main
    files: 
      - components/wavinahc9000v2/configs/channel_01.yaml 
      - components/wavinahc9000v2/configs/channel_02.yaml 
      #- components/wavinahc9000v2/configs/channel_03.yaml 
      #- components/wavinahc9000v2/configs/channel_04.yaml 
      - components/wavinahc9000v2/configs/channel_05.yaml 
      - components/wavinahc9000v2/configs/channel_06.yaml 
      - components/wavinahc9000v2/configs/channel_07.yaml 
      - components/wavinahc9000v2/configs/channel_08.yaml 
      - components/wavinahc9000v2/configs/channel_09.yaml 
      - components/wavinahc9000v2/configs/channel_10.yaml 
      #- components/wavinahc9000v2/configs/channel_11.yaml 
      #- components/wavinahc9000v2/configs/channel_12.yaml
      #- components/wavinahc9000v2/configs/channel_13.yaml 
      #- components/wavinahc9000v2/configs/channel_14.yaml
      #- components/wavinahc9000v2/configs/channel_15.yaml 
      #- components/wavinahc9000v2/configs/channel_16.yaml 
    refresh: 0s
  
modbus:
  - id: ${device}_modbus
    uart_id: uart_${device}

uart:
  - id: uart_${device}
    rx_pin: RX
    tx_pin: TX
    baud_rate: 38400
    stop_bits: 1
    parity: NONE
    
modbus_controller:
  id: ${device}_modbus_controller
  address: 1
  modbus_id: wavin_modbus
  update_interval: 5s
```

![Wavin Error](https://user-images.githubusercontent.com/55285073/159346204-065ff068-fdb5-49ca-8cb1-0b030be647a4.png)
